---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become_user: root

- name: Installs haproxy load balancer
  ansible.builtin.apt:
    name:
      - haproxy
    state: present

- name: Pushes configuration
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0640
    owner: root
    group: root
  notify:
    - restart haproxy

- name: Sets default starting flag to 1
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED"
    line: "ENABLED=1"
  notify:
    - restart haproxy
